  githelper:
    build: .
#    depends_on:
#      - local-ai-head
    ports:
      - 8086:8086
#    environment:
#      - AI_BASEURL=http://local-ai-head:8080
#      - AI_ENDPOINT=http://local-ai-head:8080
    restart: unless-stopped
